[project]
name = "durfjam2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.22.2",
    "jinja2>=3.1.6",
    "markdown2>=2.5.4",
    "pyyaml>=6.0.3",
    "weasyprint>=66.0",
]
